# SHA256 (Inhalt ab Zeile 2, d.h. dieser Datei ohne diese erste Zeile): 9745c630a06b64f58563bf7abca6dbd5607d6b2c8c16b0d47490edf393b4372b
delete_voicemail_message:
  target:
    entity:
      integration: fritzbox_anrufe
      domain: sensor
  fields:
    message_id:
      required: true
      example: "5"
      selector:
        text:
